/**
Triangle square pentagonal hexagonal heptagonal and octagonal numbers 
are all figurate polygonal numbers and are generated by the following 
formulae<table><tr><td>Triangle</td><td> </td><td>P<sub>3<i>n</i>
</sub><i>n</i><i>n</i>12</td><td> </td><td>1 3 6 10 15 </td></tr><tr>
<td>Square</td><td> </td><td>P<sub>4<i>n</i></sub><i>n</i><sup>2</sup>
</td><td> </td><td>1 4 9 16 25 </td></tr><tr><td>Pentagonal</td><td> 
</td><td>P<sub>5<i>n</i></sub><i>n</i>3<i>n</i>minus12</td><td> </td>
<td>1 5 12 22 35 </td></tr><tr><td>Hexagonal</td><td> </td><td>P<sub>6
<i>n</i></sub><i>n</i>2<i>n</i>minus1</td><td> </td><td>1 6 15 28 45 
</td></tr><tr><td>Heptagonal</td><td> </td><td>P<sub>7<i>n</i></sub>
<i>n</i>5<i>n</i>minus32</td><td> </td><td>1 7 18 34 55 </td></tr><tr>
<td>Octagonal</td><td> </td><td>P<sub>8<i>n</i></sub><i>n</i>3<i>n</i>
minus2</td><td> </td><td>1 8 21 40 65 </td></tr></table>

The ordered set of three 4digit numbers 8128 2882 8281 has three 
interesting properties<ol><li>The set is cyclic in that the last two 
digits of each number is the first two digits of the next number 
including the last number with the first</li><li>Each polygonal type 
triangle P<sub>3127</sub>8128 square P<sub>491</sub>8281 and 
pentagonal P<sub>544</sub>2882 is represented by a different number in 
the set</li><li>This is the only set of 4digit numbers with this 
property</li></ol>

Find the sum of the only ordered set of six cyclic 4digit numbers for 
which each polygonal type triangle square pentagonal hexagonal 
heptagonal and octagonal is represented by a different number in the 
set
*/
object Euler61 extends App {
  println("Euler 61")
}