/**
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms
Starting with 1 and 2 the first 10 terms will be 1 2 3 5 8 13 21 34 55 
89

Every positive integer can be uniquely written as a sum of 
nonconsecutive terms of the Fibonacci sequence For example 100  3  8  
89
Such a sum is called the <b>Zeckendorf representation</b> of the 
number

For any integer <var>n</var>0 let <var>z</var><var>n</var> be the 
number of terms in the Zeckendorf representation of <var>n</var>
Thus <var>z</var>5thinspthinsp1 <var>z</var>14thinspthinsp2 <var>z
</var>100thinspthinsp3 etc
Also for 0lt<var>n</var>lt10<sup>6</sup> 8721thinsp<var>z</var><var>n
</var>thinspthinsp7894453

Find 8721thinsp<var>z</var><var>n</var> for 0lt<var>n</var>lt10<sup>17
</sup>
*/
object Euler297 extends App {
  println("Euler 297")
}