/**
Consider all integer combinations of <i>a</i><sup><i>b</i></sup> for 2 
le <i>a</i> le 5 and 2 le <i>b</i> le 5<blockquote>2<sup>2</sup>4 2
<sup>3</sup>8 2<sup>4</sup>16 2<sup>5</sup>32
3<sup>2</sup>9 3<sup>3</sup>27 3<sup>4</sup>81 3<sup>5</sup>243
4<sup>2</sup>16 4<sup>3</sup>64 4<sup>4</sup>256 4<sup>5</sup>1024
5<sup>2</sup>25 5<sup>3</sup>125 5<sup>4</sup>625 5<sup>5</sup>3125
</blockquote>

If they are then placed in numerical order with any repeats removed we 
get the following sequence of 15 distinct terms

4 8 9 16 25 27 32 64 81 125 243 256 625 1024 3125

How many distinct terms are in the sequence generated by <i>a</i><sup>
<i>b</i></sup> for 2 le <i>a</i> le 100 and 2 le <i>b</i> le 100
*/
object Euler29 extends App {
  println("Euler 29")
}