/**
The <b>Pythagorean tree</b> is a fractal generated by the following 
procedure

Start with a unit square Then calling one of the sides its base in the 
animation the bottom side is the base<ol><li> Attach a right triangle 
to the side opposite the base with the hypotenuse coinciding with that 
side and with the sides in a 345 ratio Note that the smaller side of 
the triangle must be on the right side with respect to the base see 
animation</li><li> Attach a square to each leg of the right triangle 
with one of its sides coinciding with that leg</li><li> Repeat this 
procedure for both squares considering as their bases the sides 
touching the triangle</li></ol>The resulting figure after an infinite 
number of iterations is the Pythagorean tree<div align='center'>
<img src="project/images/p395_pythagorean.gif" />
*/
object Euler395 extends App {
  println("Euler 395")
}