/**
The sequence of triangle numbers is generated by adding the natural 
numbers So the 7<sup>th</sup> triangle number would be 1  2  3  4  5  
6  7  28 The first ten terms would be

1 3 6 10 15 21 28 36 45 55 

Let us list the factors of the first seven triangle numbers
<blockquote style="font-family:courier new;"><b> 1</b> 1
<b> 3</b> 13
<b> 6</b> 1236
<b>10</b> 12510
<b>15</b> 13515
<b>21</b> 13721
<b>28</b> 12471428</blockquote>

We can see that 28 is the first triangle number to have over five 
divisors

What is the value of the first triangle number to have over five 
hundred divisors
*/
object Euler12 extends App {
  println("Euler 12")
}