/**
Triangle pentagonal and hexagonal numbers are generated by the 
following formulae<table><tr><td>Triangle</td><td> </td><td>T<sub><i>n
</i></sub><i>n</i><i>n</i>12</td><td> </td><td>1 3 6 10 15 </td></tr>
<tr><td>Pentagonal</td><td> </td><td>P<sub><i>n</i></sub><i>n</i>3<i>n
</i>minus12</td><td> </td><td>1 5 12 22 35 </td></tr><tr><td>Hexagonal
</td><td> </td><td>H<sub><i>n</i></sub><i>n</i>2<i>n</i>minus1</td>
<td> </td><td>1 6 15 28 45 </td></tr></table>

It can be verified that T<sub>285</sub>  P<sub>165</sub>  H<sub>143
</sub>  40755

Find the next triangle number that is also pentagonal and hexagonal
*/
object Euler45 extends App {
  println("Euler 45")
}